<html>
<head>
<style>
body {
  
background-image: url("panel2.jpg");
  
}
h1{
	color:rgb(18, 18, 18);
font-family: "Courier New";
}
h5{
	color:rgb(18, 18, 18);
	font-family: "Courier New";
}
h2{
	color:rgb(18, 18, 18);
	font-family: "Courier New";
}

</style>
</head>
<body>
<h1 align="center" >ATTENDANCE MANAGEMENT SYSTEM()</h1>
<h1 align="center" >LOGIN AS:</h1>
<form align="center" action="value2.php" >
<img src="wordpress.png" width='128' height='128' /><BR>
<input type="submit" style="padding: 5px 10; border-radius: 5px; margin-top:5px; background: #000; color: fff;"; value="ADMIN" name="admin">
</form>
<form align="center" action="value5.php">
<img src="suntea.png"  width='128' height='128' /><BR>
<input type="submit" style="padding: 5px 10; border-radius: 5px; margin-top:5px; background: #000; color: fff;"; value="TEACHER" name="student">
</form>
<form align="center" action="value6.php">
<img src="sunstu.png"  width='128' height='128' /><BR>
<input type="submit" style="padding: 5px 10; border-radius: 5px; margin-top:5px; background: #000; color: fff;"; value="STUDENT" name="teacher"><br>
</form>

<br><h5 align="center">ATTENDENCE MANAGEMENT SYSTEM © VERSION 1.0.01.0</h5>
</BODY>
</HTML> 